baseURL = "https://junejun.blue"
languageCode = "en-us"
title = "June Jun"
theme="archie"
copyright = "© June Jun"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "dev | study | reviews | life"
  customCSS = ["css/custom.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pcjun97"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/pcjun97"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/pcjun97"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
